### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by gregclermont** [mathjax/asciimathml#31]
Hello,
I have just added/modified two keywords/symbols that I needed and I thought that might interest you:

Here is the code I used:
```js
MathJax.Hub.Register.StartupHook("AsciiMath Jax Config",function () {
  var AM = MathJax.InputJax.AsciiMath.AM;
  for (var i = 0; i < AM.symbols.length; i++) {
    if (AM.symbols[i].input == "->") {
      AM.symbols[i].ttype = AM.TOKEN.UNDEROVER
    }
  }
  AM.symbols.push(
    {input:"~",  tag:"mo", output:"\u223C", tex:null, ttype: AM.TOKEN.UNDEROVER}
  );
});
```

This allows for those uses (the 2nd and 4th were not possible):

![capture d ecran 2015-01-15 a 17 42 12](https://cloud.githubusercontent.com/assets/580609/5762002/785f474c-9cdf-11e4-9467-4ef245d50075.png)

I can make a PR if you think it's useful.

**Comment by pkra** [comment]
Not my call but this looks nice!

@drlippman ? @jipsen ?

**Comment by drlippman** [comment]
I believe Peter's original to stacking something over an operator was the stackrel binary operator, but it only works for stacking something over a symbol, not under.

So I think we could go two ways with this:
1) If there are other symbols currently of ttype CONST for which we would only ever want to stack something over/under them, and would never subscript/superscript them, then changing them to OVERUNDER makes sense.

2) We could add another binary operator, similar to stackrel, which would allow for placing a symbol under another, so the examples presented could be done as something like `stackunder{->}{exp}`

3) Do a combo of those.

**Comment by dpvc** [comment]
I personally like 2 the best (or perhaps 3 if there are any of the kind listed in 1, but then you run into inconsistent usage, as some symbols work one way and some another).

**Comment by drlippman** [comment]
Perhaps borrowing "overset" and "underset" from latex/amsmath would be better names than using stackrel...

Another option would be to borrow the \mathop approach, where mathop would turn a symbol from CONST to OVERUNDER.  But the complexity of that seems to run counter to the AsciiMath philosophy.

I agree a combo is probably nicest, but I don't know advanced math fields well enough to know whether any of the CONST symbols are ever super or subscripted.

**Comment by dpvc** [comment]
What I would not want to see is someone who wanted to use a super or subscript but couldn't because it became under or over.  Is there a way to override that if needed?  I like your `overset` and`underset` idea.  Can you have something that does both (or if they are combined, they produce munderover)?  There are use-cases where you have arrows with decorations both above and below, for example.

**Comment by drlippman** [comment]
Just got around to revisiting this. I think adding overset and underset is probably the simplest solution to enabling these types of symbols.  Going to go ahead and add them.
