### ISSUE TITLE
AMTparseAMtoTeX issue: Incorrect transformation of `a // b` to Latex

### ISSUE THREAD

**Issue by scaljeri** [mathjax/asciimathml#32]
I'm using `ASCIIMathTeXImg.js` to transform AsciiMath to Latex (or Tex)

    AMTparseAMtoTeX('a // b');

This global function works pretty wel, but with fractions like

    a // b

which is valid [AsciiMath](http://mathcs.chapman.edu/~jipsen/mathml/asciimath.html) it seems to go wrong. `AMTparseAMtoTeX` transforms this to:

    {a}\//{b}

Which is incorrect. Instead (I think) it should have been transformed to

    a/b

Is this a bug or is there something I do wrong here ?

One other thing, I sometimes get the following error in the console:

    Uncaught ReferenceError: AMTcgiloc is not defined

What might be the cause of this error ?

**Comment by drlippman** [comment]
It is indeed a bug.  Interestingly, one I just discovered a day or two ago.  I'll get a fix pushed out soonish. 

<div>-------- Original message --------</div><div>From: Lucas Calje <notifications@github.com> </div><div>Date:04/16/2015  12:49 AM  (GMT-08:00) </div><div>To: mathjax/asciimathml <asciimathml@noreply.github.com> </div><div>Subject: [asciimathml] AMTparseAMtoTeX issue: Incorrect transformation of `a
  // b` to Latex (#32) </div><div>
</div>I'm using ASCIIMathTeXImg.js to transform AsciiMath to Latex (or Tex)

AMTparseAMtoTeX('a // b');
This global function works pretty wel, but with fractions like

a // b
which is valid AsciiMath it seems to go wrong. AMTparseAMtoTeX transforms this to:

{a}\//{b}
Which is incorrect. Instead (I think) it should have been transformed to

a/b
Is this a bug or is there something I do wrong here ?

**Comment by scaljeri** [comment]
That would be great, thank a lot!

Although not very much related, but do you know why I get, once in a while, the `AMTcgiloc is not defined` error ?
