### ISSUE TITLE
Website for AsciiMath

### ISSUE THREAD

**Issue by adius** [mathjax/asciimathml#5]
Now that asciimath has finally it's own repo, I was thinking it would be great if asciimath also had its own website.
For example asciimath.org would still be available.
I'd be happy to help you build the website!
We could host it via github pages in it's own repo e.g mathjax/asciimath.org
What do you think?

**Comment by pkra** [comment]
This has been implemented a while ago.

**Comment by pkra** [comment]
For lurkers: https://github.com/asciimath/asciimath.github.io / http://asciimath.org/
